### ISSUE TITLE
Use consistent ClickHouse image version

### ISSUE THREAD

**Issue by bmtcril** [openedx/tutor-contrib-clickhouse#15]
In spite of there being a variable DOCKER_IMAGE_CLICKHOUSE it's not used everywhere. At least in the local-docker-compose-* files, maybe elsewhere. We should get all of these on the same version.

https://github.com/openedx/tutor-contrib-clickhouse/blob/ee68141f944d8ae1ed935d95b4148417305fcf53/tutorclickhouse/plugin.py#L24

**Comment by mariajgrimaldi** [comment]
I believe this was already solved by this PR: https://github.com/openedx/tutor-contrib-clickhouse/pull/16

**Comment by bmtcril** [comment]
Yep!
