### ISSUE TITLE
Remove default database creation

### ISSUE THREAD

**Issue by bmtcril** [openedx/tutor-contrib-clickhouse#7]
Currently a hard coded `xapi` database is created on startup. This is also happening using a configured variable in the OARS plugin, and should not be happening here according to the OARS architectural principles. We should just be able to remove this line: https://github.com/openedx/tutor-contrib-clickhouse/blob/main/tutorclickhouse/plugin.py#L125

**Comment by Ian2012** [comment]
Is this still an issue? I do not see anything related to xapi here.

Is it this one https://github.com/openedx/tutor-contrib-oars/blob/208bad59e7da72f2af9409956331aa28fdaf807a/tutoroars/templates/oars/jobs/init/oars_init_schemas_tables_users.sh#L18 ?

**Comment by bmtcril** [comment]
It happens automatically in the ClickHouse container when the CLICKHOUSE_DB env var is set. You should see it in the ClickHouse logs: `2023-05-03 15:24:19 /entrypoint.sh: create database 'xapi'`. I don't actually think it's a problem, and may actually prevent some other issues regarding timing, so I'm going to close this one out.
